/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modelo;

/**
 *
 * @author Delvi
 */
public class JFMosMediESpe extends javax.swing.JFrame {

    /**
     * Creates new form JFMosMediESpe
     */
    public JFMosMediESpe() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton2.setText("MEDICO FAMILIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 240, -1));

        jButton3.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton3.setText("MEDICO INTERNO");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 240, -1));

        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton1.setText("CIRUGIA GENERAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 240, -1));

        jButton4.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton4.setText("CARDIOLOGIA");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 240, -1));

        jButton5.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton5.setText("PEDIATRIA");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 240, -1));

        jButton6.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton6.setText("CIRUGIA PLASTICA");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 240, -1));

        jButton7.setFont(new java.awt.Font("Bahnschrift", 1, 19)); // NOI18N
        jButton7.setText("Regresar");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jButton8.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton8.setText("DERMATOLOGIA");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 280, -1));

        jButton9.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton9.setText("GINECOLOGIA Y OBSTETRICIA");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 280, -1));

        jButton10.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton10.setText("NEUROLOGIA");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 280, -1));

        jButton11.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton11.setText("TRAUMATOLOGIA Y ORTOPEDIA");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jButton12.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton12.setText("UROLOGIA");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 280, -1));

        jButton13.setFont(new java.awt.Font("Bahnschrift", 1, 17)); // NOI18N
        jButton13.setText("NEUROLOGIA");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 280, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mostrar médicos registrados por campo de especialización");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 630, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMosMediESpe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMosMediESpe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMosMediESpe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMosMediESpe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMosMediESpe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
